#!/bin/sh

set -eux

case $# in
(1)	:
	;;
(*)	echo 1>&2 'usage: cover [fuzz-target]'
	exit 1
	;;
esac

target="$1"
html="fuzz/coverage/$target.html"

cargo +nightly fuzz run "$target" -- -max_total_time=10
cargo +nightly fuzz coverage "$target"

cargo +nightly cov -- \
      show -Xdemangler=rustfilt \
      fuzz/target/*/release/"$target" \
      --instr-profile=fuzz/coverage/"$target"/coverage.profdata \
      --name-regex=dnstrie.* \
      --format=html >"$html"

open "$html"
